name: black-autoformat

on: [push, pull_request]

jobs:
  black-autoformat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          options: "--check --diff --safe --target-version py310"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: autoformatted by black
